import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { gzipSync } from 'node:zlib';
const html=readFileSync('dist/index.html','utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const style=html.match(/<style>([\s\S]*?)<\/style>/)[1];
const policy=html.match(/http-equiv="Content-Security-Policy" content="([^"]+)"/)[1];
const hash=s=>createHash('sha256').update(s).digest('base64');
assert.ok(policy.includes(`'sha256-${hash(script)}'`));
assert.ok(policy.includes(`'sha256-${hash(style)}'`));
assert.ok(!script.includes('\r'));assert.ok(!style.includes('\r'));
const sourceStyle=readFileSync('site/style.css','utf8').replace(/\r\n?/g,'\n');
assert.equal(style,sourceStyle);
assert.ok(policy.includes("connect-src 'self'"));
assert.ok(!policy.includes('unsafe-inline'));assert.ok(!policy.includes('unsafe-eval'));
const sources=readdirSync('src').filter(x=>x.endsWith('.ts')).map(x=>readFileSync(`src/${x}`,'utf8')).join('\n');
for(const bad of [/\.innerHTML\s*=/,/\beval\s*\(/,/new\s+Function\s*\(/,/document\.write\s*\(/,/new\s+WebSocket\s*\(/,/setInterval\s*\(/,/on(?:click|load|error)=/])assert.ok(!bad.test(sources),String(bad));
assert.equal((sources.match(/\bfetch\s*\(/g)??[]).length,3);
assert.ok(sources.includes("const LEADERBOARD_ENDPOINT = '/api/leaderboard';"));
assert.ok(sources.includes("const RUN_SESSIONS_ENDPOINT = '/api/run-sessions';"));
assert.ok(!/fetch\s*\(\s*['\"]https?:/i.test(sources));
assert.ok(!/<script[^>]+src=/i.test(html));assert.ok(!/@import\b/i.test(style));
const pkg=JSON.parse(readFileSync('package.json','utf8'));
assert.equal(Object.keys(pkg.dependencies??{}).length,0);
assert.ok(Buffer.byteLength(html)<110*1024);assert.ok(gzipSync(html).length<30*1024);
const manifest=JSON.parse(readFileSync('dist/manifest.json','utf8'));
assert.equal(manifest.sha256,createHash('sha256').update(html).digest('hex'));
const report={result:'PASS',checks:['Exact script CSP hash','Exact stylesheet CSP hash','No unsafe-inline or unsafe-eval','Network restricted to same origin','Exactly three allowlisted same-origin leaderboard/session fetch call sites','No HTML string sinks','No runtime code evaluation','No WebSocket/interval loops in app','No third-party script or stylesheet loads','Zero runtime dependencies','Under 110 KiB raw / 30 KiB gzip','Build SHA-256 matches manifest'],htmlBytes:Buffer.byteLength(html),gzipBytes:gzipSync(html).length,scope:'Bounded static checks, not a complete security audit or proof.'};
writeFileSync('qa/static-audit.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
