import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { gzipSync } from 'node:zlib';
const html=readFileSync('dist/index.html','utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const style=html.match(/<style>([\s\S]*?)<\/style>/)[1];
const policy=html.match(/http-equiv="Content-Security-Policy" content="([^"]+)"/)[1];
const hash=s=>createHash('sha256').update(s).digest('base64');
assert.ok(policy.includes(`'sha256-${hash(script)}'`));
assert.ok(policy.includes(`'sha256-${hash(style)}'`));
assert.ok(!script.includes('\r'));assert.ok(!style.includes('\r'));
const sourceStyle=readFileSync('site/style.css','utf8').replace(/\r\n?/g,'\n');
assert.equal(style,sourceStyle);
assert.ok(policy.includes("connect-src 'self'"));
assert.ok(!policy.includes('unsafe-inline'));assert.ok(!policy.includes('unsafe-eval'));
const sources=readdirSync('src').filter(x=>x.endsWith('.ts')).map(x=>readFileSync(`src/${x}`,'utf8')).join('\n');
for(const bad of [/\.innerHTML\s*=/,/\beval\s*\(/,/new\s+Function\s*\(/,/document\.write\s*\(/,/new\s+WebSocket\s*\(/,/setInterval\s*\(/,/on(?:click|load|error)=/])assert.ok(!bad.test(sources),String(bad));
assert.equal((sources.match(/\bfetch\s*\(/g)??[]).length,3);
assert.ok(sources.includes("const LEADERBOARD_ENDPOINT = '/api/leaderboard';"));
assert.ok(sources.includes("const RUN_SESSIONS_ENDPOINT = '/api/run-sessions';"));
assert.ok(!/fetch\s*\(\s*['\"]https?:/i.test(sources));
assert.ok(!/<script[^>]+src=/i.test(html));assert.ok(!/@import\b/i.test(style));
const pkg=JSON.parse(readFileSync('package.json','utf8'));
assert.equal(Object.keys(pkg.dependencies??{}).length,0);
const htmlBytes=Buffer.byteLength(html),gzipBytes=gzipSync(html,{level:9}).length,rawBudget=124*1024,gzipBudget=39*1024;
assert.ok(htmlBytes<rawBudget,`Artifact ${htmlBytes} bytes exceeds the raw release limit ${rawBudget} by ${htmlBytes-rawBudget+1} bytes`);
assert.ok(gzipBytes<gzipBudget,`Artifact ${gzipBytes} gzip bytes exceeds the gzip release limit ${gzipBudget} by ${gzipBytes-gzipBudget+1} bytes`);
const manifest=JSON.parse(readFileSync('dist/manifest.json','utf8'));
assert.equal(manifest.sha256,createHash('sha256').update(html).digest('hex'));
assert.equal(manifest.htmlBytes,htmlBytes);
assert.equal(manifest.gzipBytes,gzipBytes);
const report={result:'PASS',checks:['Exact script CSP hash','Exact stylesheet CSP hash','No unsafe-inline or unsafe-eval','Network restricted to same origin','Exactly three allowlisted same-origin leaderboard/session fetch call sites','No HTML string sinks','No runtime code evaluation','No WebSocket/interval loops in app','No third-party script or stylesheet loads','Zero runtime dependencies','Under 124 KiB raw / 39 KiB gzip release budget','Build size and SHA-256 match manifest'],htmlBytes,gzipBytes,sizeBudget:{rawBytes:rawBudget,gzipBytes:gzipBudget},scope:'Bounded static checks, not a complete security audit or proof.'};
writeFileSync('qa/static-audit.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
